Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,43 +1,59 @@
-name: Build,Analyze,scan
+name: Build, Analyze, Scan
+
 on:
   push:
     branches:
       - main
+
 jobs:
   build-analyze-scan:
     name: Build
     runs-on: [self-hosted, linux, X64]
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0
+
       - name: Build and analyze with SonarQube
         uses: sonarsource/sonarqube-scan-action@master
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      - name: npm install dependency
+
+      - name: Install npm dependencies
         run: npm install
+
       - name: Trivy file scan
         run: trivy fs . > trivyfs.txt
-      - name: Docker Build and push
+
+      - name: Docker Build and Push
         run: |
+          echo "Logging into DockerHub..."
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "Missing DockerHub credentials. Exiting..."
+            exit 1
+          fi
           docker build -t tic-tac-toe .
           docker tag tic-tac-toe janal024/tic-tac-toe:latest
           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
           docker push janal024/tic-tac-toe:latest
         env:
           DOCKER_CLI_ACI: 1
-      - name: Image scan
+
+      - name: Trivy image scan
         run: trivy image janal024/tic-tac-toe:latest > trivyimage.txt
+
   deploy:
-   needs: build-analyze-scan
-   runs-on: [self-hosted, linux, X64]
-   steps:
-      - name: docker pull image
+    needs: build-analyze-scan
+    runs-on: [self-hosted, linux, X64]
+    steps:
+      - name: Docker pull image
         run: docker pull janal024/tic-tac-toe:latest
-      - name: Image scan
+
+      - name: Image scan after pull
         run: trivy image janal024/tic-tac-toe:latest > trivyimagedeploy.txt
-      - name: Deploy to container
+
+      - name: Deploy container
         run: docker run -d --name game -p 3000:3000 janal024/tic-tac-toe
